# Generated by Django 5.1.5 on 2026-08-06 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_threshold', models.PositiveSmallIntegerField(default=80, help_text='AI filtr chegara balli')),
                ('deal_commission_percent', models.DecimalField(decimal_places=2, default=1.5, help_text='Platforma komissiyasi (muvaffaqiyatli bitimdan), %', max_digits=5)),
                ('contract_price', models.PositiveIntegerField(default=50000, help_text="Onlayn shartnoma xizmat haqi, so'm")),
                ('vip_price', models.PositiveIntegerField(default=200000, help_text="VIP joylashuv narxi, so'm/hafta")),
                ('premium_post_price', models.PositiveIntegerField(default=70000, help_text="Premium e'lon narxi, so'm/oy")),
                ('agent_commission_percent', models.DecimalField(decimal_places=2, default=2, help_text='Uyimiz Agent fiks komissiyasi, %', max_digits=4)),
                ('platform_share_percent', models.DecimalField(decimal_places=2, default=12, help_text='Platformaning agentdan ulushi, %', max_digits=5)),
                ('agent_subscription_price', models.PositiveIntegerField(default=400000, help_text='Agent oylik obunasi')),
                ('stage', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Platforma sozlamalari',
                'verbose_name_plural': 'Platforma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price_label', models.CharField(help_text="Masalan '70 000 so\\'m' yoki 'Bepul'", max_length=64)),
                ('period', models.CharField(blank=True, help_text='oy / hafta / shartnoma / yil / —', max_length=32)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_label', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=200)),
                ('object_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('score', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='listings.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
