# Generated by Django 5.1.5 on 2026-08-06 10:48

import django.db.models.deletion
import django.utils.timezone
import listings.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='listings.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.CharField(choices=[('sale', 'Sotish'), ('rent', 'Ijara'), ('daily', 'Kunlik ijara')], default='sale', max_length=8)),
                ('district', models.CharField(db_index=True, max_length=64)),
                ('address', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('rooms', models.PositiveSmallIntegerField(default=1)),
                ('area', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=7)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('year', models.PositiveSmallIntegerField(default=2020)),
                ('ptype', models.CharField(choices=[('apartment', 'Kvartira'), ('newbuild', 'Yangi qurilish'), ('house', 'Hovli uy'), ('commercial', 'Tijorat')], default='apartment', max_length=16)),
                ('repair', models.CharField(choices=[('euro', 'Yevro remont'), ('designer', 'Dizaynerlik'), ('good', "O'rtacha"), ('average', 'Qoniqarli'), ('none', "Ta'mirsiz")], default='good', max_length=16)),
                ('docs', models.CharField(choices=[('ready', 'Hujjatlar tayyor'), ('process', 'Rasmiylashtirilmoqda')], default='ready', max_length=16)),
                ('features', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(default=False, help_text='Real foto/joylashuv tasdiqlangan (AI + admin)')),
                ('contract_ready', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('rejected', 'Rad etilgan'), ('dealt', 'Bitim tuzilgan'), ('archived', 'Arxiv')], default='pending', max_length=12)),
                ('badge', models.CharField(choices=[('oddiy', 'Oddiy'), ('premium', 'Premium'), ('vip', 'VIP')], default='oddiy', max_length=8)),
                ('promoted_until', models.DateTimeField(blank=True, null=True)),
                ('rating_avg', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_listings', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal', models.CharField(choices=[('sale', 'Sotish'), ('rent', 'Ijara'), ('daily', 'Kunlik ijara')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('service_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('seller_signed', models.BooleanField(default=True)),
                ('buyer_signed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Loyihada'), ('signed', 'Imzolangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=12)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=listings.models.contract_pdf_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_seller', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='listings.listing')),
            ],
        ),
        migrations.AddField(
            model_name='chatthread',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='listings.listing'),
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=listings.models.listing_photo_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='listings.listing')),
            ],
            options={
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatthread',
            unique_together={('listing', 'buyer')},
        ),
    ]
