# Generated by Django 5.1.5 on 2026-08-06 10:48

import accounts.models
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='Foydalanuvchi', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('agent', 'Uyimiz Agent'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], db_index=True, default='user', max_length=16)),
                ('user_kind', models.CharField(choices=[('owner', 'Uy egasi'), ('buyer', 'Xaridor'), ('tenant', 'Ijarachi')], default='buyer', max_length=16)),
                ('verified', models.BooleanField(default=False, help_text='myID yoki SMS orqali tasdiqlangan')),
                ('avatar_initials', models.CharField(blank=True, max_length=4)),
                ('district', models.CharField(blank=True, help_text='Agent uchun biriktirilgan hudud', max_length=64)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('Yangi', 'Yangi agent'), ('Faol', 'Faol makler'), ('Tajribali', 'Tajribali makler'), ('Top', 'Top Makler')], default='Yangi', max_length=16)),
                ('certification', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Rad etilgan', 'Rad etilgan'), ('Bekor qilindi', 'Bekor qilindi')], default='Kutilmoqda', max_length=20)),
                ('platform_share', models.PositiveSmallIntegerField(default=12, help_text='Platformaning agentdan ulushi, %')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('avg_response_minutes', models.PositiveIntegerField(default=0)),
                ('historical_deals', models.PositiveIntegerField(default=0)),
                ('total_deals', models.PositiveIntegerField(default=0)),
                ('admin_title', models.CharField(blank=True, choices=[('Superadmin', 'Superadmin'), ('Admin', 'Admin'), ('Moderator', 'Moderator')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
