# Generated by Django 5.1.5 on 2026-08-06 10:48

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('request', models.CharField(help_text='Masalan: 3 xona, Chilonzor', max_length=150)),
                ('deal_type', models.CharField(choices=[('Sotib olish', 'Sotib olish'), ('Ijara', 'Ijara'), ('Kunlik', 'Kunlik')], default='Sotib olish', max_length=16)),
                ('district', models.CharField(blank=True, max_length=64)),
                ('budget_label', models.CharField(blank=True, max_length=64)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('status', models.CharField(choices=[("Qo'ng'iroq kutmoqda", "Qo'ng'iroq kutmoqda"), ("Ko'rsatuv belgilandi", "Ko'rsatuv belgilandi"), ('Fotoga chiqish', 'Fotoga chiqish'), ('Shartnomada', 'Shartnomada'), ('Yopilgan', 'Yopilgan'), ('Rad etilgan', 'Rad etilgan')], default="Qo'ng'iroq kutmoqda", max_length=32)),
                ('source', models.CharField(choices=[('Mobil ilova', 'Mobil ilova'), ('Web', 'Web'), ('Telegram', 'Telegram')], default='Web', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mijoz', 'Yangi mijoz'), ("qo'ng'iroq", "Qo'ng'iroq"), ("ko'rsatuv", "Ko'rsatuv"), ('bitim', 'Bitim'), ('shartnoma', 'Shartnoma'), ('reyting', 'Reyting')], max_length=16)),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.client')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(help_text="Platformadagi e'lon ID", max_length=16, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=200)),
                ('deal_type', models.CharField(choices=[('Sotib olish', 'Sotib olish'), ('Ijara', 'Ijara'), ('Kunlik', 'Kunlik')], default='Sotib olish', max_length=16)),
                ('price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('rooms', models.PositiveSmallIntegerField(default=1)),
                ('area', models.DecimalField(decimal_places=1, max_digits=6)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('total_floors', models.PositiveSmallIntegerField(default=1)),
                ('built_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Faol', 'Faol'), ('Band', 'Band'), ('Sotilgan', 'Sotilgan'), ('Arxiv', 'Arxiv')], default='Faol', max_length=16)),
                ('badge', models.CharField(choices=[('Oddiy', 'Oddiy'), ('VIP', 'VIP'), ('Premium', 'Premium')], default='Oddiy', max_length=16)),
                ('is_verified', models.BooleanField(default=True)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('owner_phone', models.CharField(blank=True, max_length=32)),
                ('photo_count', models.PositiveSmallIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('public_listing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_property', to='listings.listing')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[("Ko'rsatuv", "Ko'rsatuv"), ('Kelishuv', 'Kelishuv'), ('Shartnoma', 'Shartnoma'), ('Yopilgan', 'Yopilgan'), ('Bekor qilingan', 'Bekor qilingan')], default="Ko'rsatuv", max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('commission', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('platform_cut', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('contract_signed', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.client')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=crm.models.listing_photo_path)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='crm.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('Rejalashtirilgan', 'Rejalashtirilgan'), ("Bo'lib o'tdi", "Bo'lib o'tdi"), ('Bekor qilingan', 'Bekor qilingan')], default='Rejalashtirilgan', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='crm.client')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='crm.property')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
